### Добавить вопрос
GET http://localhost:8080/java/add?question=q1&answer=a1

### Добавить вопрос
GET http://localhost:8080/java/add?question=q2&answer=a2

### Добавить вопрос
GET http://localhost:8080/java/add?question=q3&answer=a3

### Добавить вопрос
GET http://localhost:8080/java/add?question=q4&answer=a4

### Добавить вопрос
GET http://localhost:8080/java/add?question=q5&answer=a5

### Получить вопросы
GET http://localhost:8080/java

### Удалить вопрос
GET http://localhost:8080/java/remove?question=q2&answer=a2

### Получиить несколько вопросов
GET http://localhost:8080/get/10

### Получиить несколько вопросов
GET http://localhost:8080/get/3
